version: '3.8'

services:
  db:
    image: postgres
    container_name: academy-postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432" # Máy thật dùng 5433, trong Docker dùng 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: